### ISSUE TITLE
[STRY/QE] Automated storyboard and tags.

### ISSUE THREAD

**Issue by b2wu** [cse110-sp21-group13/cse110-sp21-group13#12]
**Briefly Describe the Feature-Set for the Story**

Implementing automated tags and labels. 
**Layout acceptance criteria**

Relevant labels are added when an issue is created or removed. 

**Additional context (optional)**
Any additional information you'd like to include.

**Comment by bchaing** [comment]
Specific tags for storyboard columns were never implemented.
