### ISSUE TITLE
[STRY/QE] Looking to W3 HTML verifier 

### ISSUE THREAD

**Issue by b2wu** [cse110-sp21-group13/cse110-sp21-group13#13]
**Briefly Describe the Feature-Set for the Story**

Implement HTML verifier for pull requests. 

**Layout acceptance criteria**

Pull request if HTML passes tests. 

**Additional context (optional)**
Any additional information you'd like to include.

**Comment by bchaing** [comment]
It is too late in the process to add this without fear of reworking large parts of the code base.
