### ISSUE TITLE
[STRY/QE] Automate Approvals

### ISSUE THREAD

**Issue by b2wu** [cse110-sp21-group13/cse110-sp21-group13#15]
**Briefly Describe the Feature-Set for the Story**

Implement GitHub actions to automatically legal pull requests when approved. 

**Layout acceptance criteria**

Pull requests are automatically merged when reaching a certain number of reviews. 

**Additional context (optional)**
Any additional information you'd like to include.

**Comment by bchaing** [comment]
A pull request process has already been established, this feature is unnecessary.
