### ISSUE TITLE
[STRY/FE] Create Homepage HTML Page

### ISSUE THREAD

**Issue by cnazemi** [cse110-sp21-group13/cse110-sp21-group13#17]
**Briefly Describe the Feature-Set for the Story**
Create landing page, the first page a user sees to welcome them.

**Layout acceptance criteria**
Create an HTML file, on this file add info text and "Get Started" button.

**Additional context (optional)**
Omit navigation bar until it's completed (Add code in after completion).

https://github.com/cse110-sp21-group13/cse110-sp21-group13/tree/main/specs/interface/highfidelity

**Comment by lvlahaki** [comment]
Reopened to make minor edit to file path for logo src
